[project]
name = "lab3"
version = "0.1.0"
description = "This is a CRUD compliant event booking cli for Fountain View Hall"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "holidays>=0.97",
    "questionary>=2.1.1",
]

[tool.uv]
package = true

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "lefthook>=2.1.9",
]

[project.scripts]
main = "lab3.main:main"

[tool.hatch.build.targets.wheel]
packages = ["src/lab3"]
